project_id = "caamfzlasjlfjxzypjxx"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.plinqpay-checkout]
verify_jwt = false

[functions.plinqpay-webhook]
verify_jwt = false
